/*
 * Copyright 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package somepackage;

import com.google.android.libraries.remixer.Callback;
import com.google.android.libraries.remixer.ItemListVariable;
import com.google.android.libraries.remixer.Remixer;
import com.google.android.libraries.remixer.Variable;
import com.google.android.libraries.remixer.annotation.RemixerBinder;
import java.lang.Integer;
import java.lang.Override;
import java.util.ArrayList;

/**
 * This class was generated by RemixerAnnotationProcessor */
public class Correct_RemixerBinder implements RemixerBinder.Binder<Correct> {
  @Override
  public void bindInstance(Correct activity) {
    Remixer remixer = Remixer.getInstance();
    Generated_setColor setColor_callback = new Generated_setColor(activity);
    ItemListVariable.Builder<Integer> setColor_remixer_item = new ItemListVariable.Builder<Integer>();
    setColor_remixer_item.setDataType(Remixer.getInstance().getDataType("__DataTypeColor__"));
    setColor_remixer_item.setKey("setColor");
    setColor_remixer_item.setTitle("setColor");
    setColor_remixer_item.setLayoutId(0);
    setColor_remixer_item.setContext(activity);
    setColor_remixer_item.setCallback(setColor_callback);
    ArrayList<Integer> setColor_variable_list = new ArrayList<Integer>();
    setColor_variable_list.add(1);
    setColor_variable_list.add(2);
    setColor_remixer_item.setLimitedToValues(setColor_variable_list);
    setColor_remixer_item.setInitialValue(1);
    remixer.addItem(setColor_remixer_item.build());
  }

  static class Generated_setColor implements Callback<Integer> {
    private final Correct activity;

    Generated_setColor(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<Integer> variable) {
      activity.setColor(variable.getSelectedValue());
    }
  }
}



