/*
 * Copyright 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package somepackage;

import com.google.android.libraries.remixer.Callback;
import com.google.android.libraries.remixer.RangeVariable;
import com.google.android.libraries.remixer.Remixer;
import com.google.android.libraries.remixer.Variable;
import com.google.android.libraries.remixer.annotation.RemixerBinder;
import java.lang.Integer;
import java.lang.Override;

/**
 * This class was generated by RemixerAnnotationProcessor */
public class FixesDefaultValue_RemixerBinder implements RemixerBinder.Binder<FixesDefaultValue> {
  @Override
  public void bindInstance(FixesDefaultValue activity) {
    Remixer remixer;
    if (activity.remixer == null) {
      remixer = Remixer.getInstance();
    } else {
      remixer = activity.remixer;
    }
    Generated_fixValue fixValue_callback = new Generated_fixValue(activity);
    RangeVariable fixValue_variable = new RangeVariable("fixValue", "fixValue", 15, 15, 100, 1, fixValue_callback, 0);
    fixValue_variable.init();
    remixer.addItem(fixValue_variable);
    activity.remixer = remixer;
  }

  static class Generated_fixValue implements Callback<Integer> {
    private final FixesDefaultValue activity;

    Generated_fixValue(FixesDefaultValue activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<Integer> variable) {
      activity.fixValue(variable.getSelectedValue());
    }
  }
}
