/*
 * Copyright 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package somepackage;

import com.google.android.libraries.remixer.BooleanVariableBuilder;
import com.google.android.libraries.remixer.Callback;
import com.google.android.libraries.remixer.ItemListVariable;
import com.google.android.libraries.remixer.RangeVariable;
import com.google.android.libraries.remixer.Remixer;
import com.google.android.libraries.remixer.StringVariableBuilder;
import com.google.android.libraries.remixer.Variable;
import com.google.android.libraries.remixer.annotation.RemixerBinder;
import java.lang.Boolean;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.ArrayList;

/**
 * This class was generated by RemixerAnnotationProcessor */
public class Correct_RemixerBinder implements RemixerBinder.Binder<Correct> {
  @Override
  public void bindInstance(Correct activity) {
    Remixer remixer = Remixer.getInstance();
    Generated_setBoolean setBoolean_callback = new Generated_setBoolean(activity);
    BooleanVariableBuilder setBoolean_remixer_item = new BooleanVariableBuilder();
    setBoolean_remixer_item.setDataType(Remixer.getInstance().getDataType("__DataTypeBoolean__"));
    setBoolean_remixer_item.setKey("setBoolean");
    setBoolean_remixer_item.setTitle("setBoolean");
    setBoolean_remixer_item.setLayoutId(0);
    setBoolean_remixer_item.setContext(activity);
    setBoolean_remixer_item.setCallback(setBoolean_callback);
    setBoolean_remixer_item.setInitialValue(false);
    remixer.addItem(setBoolean_remixer_item.build());
    Generated_setFloatList setFloatList_callback = new Generated_setFloatList(activity);
    ItemListVariable.Builder<Float> setFloatList_remixer_item = new ItemListVariable.Builder<Float>();
    setFloatList_remixer_item.setDataType(Remixer.getInstance().getDataType("__DataTypeNumber__"));
    setFloatList_remixer_item.setKey("setFloatList");
    setFloatList_remixer_item.setTitle("setFloatList");
    setFloatList_remixer_item.setLayoutId(0);
    setFloatList_remixer_item.setContext(activity);
    setFloatList_remixer_item.setCallback(setFloatList_callback);
    ArrayList<Float> setFloatList_variable_list = new ArrayList<Float>();
    setFloatList_variable_list.add(1f);
    setFloatList_variable_list.add(2f);
    setFloatList_variable_list.add(3f);
    setFloatList_remixer_item.setLimitedToValues(setFloatList_variable_list);
    setFloatList_remixer_item.setInitialValue(1f);
    remixer.addItem(setFloatList_remixer_item.build());
    Generated_setColorList setColorList_callback = new Generated_setColorList(activity);
    ItemListVariable.Builder<Integer> setColorList_remixer_item = new ItemListVariable.Builder<Integer>();
    setColorList_remixer_item.setDataType(Remixer.getInstance().getDataType("__DataTypeColor__"));
    setColorList_remixer_item.setKey("setColorList");
    setColorList_remixer_item.setTitle("setColorList");
    setColorList_remixer_item.setLayoutId(0);
    setColorList_remixer_item.setContext(activity);
    setColorList_remixer_item.setCallback(setColorList_callback);
    ArrayList<Integer> setColorList_variable_list = new ArrayList<Integer>();
    setColorList_variable_list.add(1);
    setColorList_variable_list.add(2);
    setColorList_variable_list.add(3);
    setColorList_remixer_item.setLimitedToValues(setColorList_variable_list);
    setColorList_remixer_item.setInitialValue(1);
    remixer.addItem(setColorList_remixer_item.build());
    Generated_setFloat setFloat_callback = new Generated_setFloat(activity);
    RangeVariable.Builder setFloat_remixer_item = new RangeVariable.Builder();
    setFloat_remixer_item.setDataType(Remixer.getInstance().getDataType("__DataTypeNumber__"));
    setFloat_remixer_item.setKey("setFloat");
    setFloat_remixer_item.setTitle("setFloat");
    setFloat_remixer_item.setLayoutId(0);
    setFloat_remixer_item.setContext(activity);
    setFloat_remixer_item.setCallback(setFloat_callback);
    setFloat_remixer_item.setMinValue(0f);
    setFloat_remixer_item.setMaxValue(100f);
    setFloat_remixer_item.setInitialValue(0f);
    setFloat_remixer_item.setIncrement(1f);
    remixer.addItem(setFloat_remixer_item.build());
    Generated_setString setString_callback = new Generated_setString(activity);
    StringVariableBuilder setString_remixer_item = new StringVariableBuilder();
    setString_remixer_item.setDataType(Remixer.getInstance().getDataType("__DataTypeString__"));
    setString_remixer_item.setKey("setString");
    setString_remixer_item.setTitle("setString");
    setString_remixer_item.setLayoutId(0);
    setString_remixer_item.setContext(activity);
    setString_remixer_item.setCallback(setString_callback);
    setString_remixer_item.setInitialValue("");
    remixer.addItem(setString_remixer_item.build());
    Generated_setStringList setStringList_callback = new Generated_setStringList(activity);
    ItemListVariable.Builder<String> setStringList_remixer_item = new ItemListVariable.Builder<String>();
    setStringList_remixer_item.setDataType(Remixer.getInstance().getDataType("__DataTypeString__"));
    setStringList_remixer_item.setKey("setStringList");
    setStringList_remixer_item.setTitle("setStringList");
    setStringList_remixer_item.setLayoutId(0);
    setStringList_remixer_item.setContext(activity);
    setStringList_remixer_item.setCallback(setStringList_callback);
    ArrayList<String> setStringList_variable_list = new ArrayList<String>();
    setStringList_variable_list.add("hello");
    setStringList_variable_list.add("world");
    setStringList_remixer_item.setLimitedToValues(setStringList_variable_list);
    setStringList_remixer_item.setInitialValue("hello");
    remixer.addItem(setStringList_remixer_item.build());
  }

  static class Generated_setBoolean implements Callback<Boolean> {
    private final Correct activity;

    Generated_setBoolean(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<Boolean> variable) {
      activity.setBoolean(variable.getSelectedValue());
    }
  }

  static class Generated_setFloatList implements Callback<Float> {
    private final Correct activity;

    Generated_setFloatList(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<Float> variable) {
      activity.setFloatList(variable.getSelectedValue());
    }
  }

  static class Generated_setColorList implements Callback<Integer> {
    private final Correct activity;

    Generated_setColorList(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<Integer> variable) {
      activity.setColorList(variable.getSelectedValue());
    }
  }

  static class Generated_setFloat implements Callback<Float> {
    private final Correct activity;

    Generated_setFloat(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<Float> variable) {
      activity.setFloat(variable.getSelectedValue());
    }
  }

  static class Generated_setString implements Callback<String> {
    private final Correct activity;

    Generated_setString(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<String> variable) {
      activity.setString(variable.getSelectedValue());
    }
  }

  static class Generated_setStringList implements Callback<String> {
    private final Correct activity;

    Generated_setStringList(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<String> variable) {
      activity.setStringList(variable.getSelectedValue());
    }
  }
}
