/*
 * Copyright 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package somepackage;

import com.google.android.libraries.remixer.BooleanRemix;
import com.google.android.libraries.remixer.ItemListRemix;
import com.google.android.libraries.remixer.RangeRemix;
import com.google.android.libraries.remixer.Remix;
import com.google.android.libraries.remixer.RemixCallback;
import com.google.android.libraries.remixer.Remixer;
import com.google.android.libraries.remixer.StringRemix;
import com.google.android.libraries.remixer.annotation.RemixerBinder;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.ArrayList;

/**
 * This class was generated by RemixerAnnotationProcessor */
class Correct_RemixerBinder extends RemixerBinder.Binder<Correct> {
  @Override
  public void bindInstance(Correct activity) {
    Remixer remixer;
    if (activity.remixer == null) {
      remixer = new Remixer();
    } else {
      remixer = activity.remixer;
    }
    Correct_setBoolean_setBoolean setBoolean_callback = new Correct_setBoolean_setBoolean(activity);
    BooleanRemix setBoolean_remix = new BooleanRemix("setBoolean", "setBoolean", false, setBoolean_callback, 0);
    remixer.addRemix(setBoolean_remix);
    Correct_setInt_setInt setInt_callback = new Correct_setInt_setInt(activity);
    RangeRemix setInt_remix = new RangeRemix("setInt", "setInt", 0, 0, 100, setInt_callback, 0);
    remixer.addRemix(setInt_remix);
    Correct_setString_setString setString_callback = new Correct_setString_setString(activity);
    StringRemix setString_remix = new StringRemix("setString", "setString", "", setString_callback, 0);
    remixer.addRemix(setString_remix);
    ArrayList<String> setStringList_remix_list = new ArrayList<String>();
    setStringList_remix_list.add("hello");
    setStringList_remix_list.add("world");
    Correct_setStringList_setStringList setStringList_callback = new Correct_setStringList_setStringList(activity);
    ItemListRemix<String> setStringList_remix = new ItemListRemix<String>("setStringList", "setStringList", "hello", setStringList_remix_list, setStringList_callback, 0);
    remixer.addRemix(setStringList_remix);
    activity.remixer = remixer;
  }

  static class Correct_setBoolean_setBoolean implements RemixCallback<Boolean> {
    private final Correct activity;

    Correct_setBoolean_setBoolean(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Remix<Boolean> remix) {
      activity.setBoolean(remix.getSelectedValue());
    }
  }

  static class Correct_setInt_setInt implements RemixCallback<Integer> {
    private final Correct activity;

    Correct_setInt_setInt(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Remix<Integer> remix) {
      activity.setInt(remix.getSelectedValue());
    }
  }

  static class Correct_setString_setString implements RemixCallback<String> {
    private final Correct activity;

    Correct_setString_setString(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Remix<String> remix) {
      activity.setString(remix.getSelectedValue());
    }
  }

  static class Correct_setStringList_setStringList implements RemixCallback<String> {
    private final Correct activity;

    Correct_setStringList_setStringList(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Remix<String> remix) {
      activity.setStringList(remix.getSelectedValue());
    }
  }
}
