/*
 * Copyright 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package somepackage;

    import com.google.android.libraries.remixer.Callback;
    import com.google.android.libraries.remixer.ItemListVariable;
    import com.google.android.libraries.remixer.Remixer;
    import com.google.android.libraries.remixer.Variable;
    import com.google.android.libraries.remixer.annotation.RemixerBinder;
    import java.lang.Float;
    import java.lang.Override;
    import java.util.ArrayList;

/**
 * This class was generated by RemixerAnnotationProcessor */
public class Correct_RemixerBinder implements RemixerBinder.Binder<Correct> {
  @Override
  public void bindInstance(Correct activity) {
    Remixer remixer = Remixer.getInstance();
    Generated_setNumber setNumber_callback = new Generated_setNumber(activity);
    ItemListVariable.Builder<Float> setNumber_remixer_item = new ItemListVariable.Builder<Float>();
    setNumber_remixer_item.setDataType(Remixer.getInstance().getDataType("__DataTypeNumber__"));
    setNumber_remixer_item.setKey("setNumber");
    setNumber_remixer_item.setTitle("setNumber");
    setNumber_remixer_item.setLayoutId(0);
    setNumber_remixer_item.setContext(activity);
    setNumber_remixer_item.setCallback(setNumber_callback);
    ArrayList<Float> setNumber_variable_list = new ArrayList<Float>();
    setNumber_variable_list.add(1f);
    setNumber_variable_list.add(2f);
    setNumber_remixer_item.setLimitedToValues(setNumber_variable_list);
    setNumber_remixer_item.setInitialValue(1f);
    remixer.addItem(setNumber_remixer_item.build());
  }

  static class Generated_setNumber implements Callback<Float> {
    private final Correct activity;

    Generated_setNumber(Correct activity) {
      this.activity = activity;
    }

    @Override
    public void onValueSet(Variable<Float> variable) {
      activity.setNumber(variable.getSelectedValue());
    }
  }
}
